on: push

name: CI

jobs:
  eslint:
    name: Up-to-date docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: make build
      - name: Check uncommitted changes
        run: test -z "$(git status --porcelain)"
